# Generated by Django 4.2.3 on 2023-07-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_meet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='desc',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='meet',
            old_name='img',
            new_name='im',
        ),
        migrations.RenameField(
            model_name='meet',
            old_name='name',
            new_name='n',
        ),
    ]
